server:
    port: 5000
spring:
    datasource:
        password: ${DB_PSW}
        url: ${DB_URL}
        username: ${DB_USER}
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: none
            show-sql: true
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
